### ISSUE TITLE
Social Share for Donation Version

### ISSUE THREAD

**Issue by therealgardenia** [itsMakeable/SA-holiday#15]
Social share text for original version: 
Join me in supporting Success Academy this holiday season! (link)

**Comment by therealgardenia** [comment]
![holidayappeal_socialshare](https://cloud.githubusercontent.com/assets/5920375/11008746/a83df216-84a0-11e5-8508-fe61b83c2284.jpg)

Social Share Image attached.

**Comment by kylamedina** [comment]
I need the Success Academy Facebook app id in order to open the popup

**Comment by therealgardenia** [comment]
Unable to test. clicking Facebook opens Twitter share. Twitter share doesn't work.

**Comment by therealgardenia** [comment]
LIVE APP ID: 
201266183541405

**Comment by therealgardenia** [comment]
TEST APP ID:
201266543541369

**Comment by therealgardenia** [comment]
Sharing works on Test site. Image not showing but has been logged as a new issue.
