### ISSUE TITLE
Donation Thank You page

### ISSUE THREAD

**Issue by therealgardenia** [itsMakeable/SA-holiday#43]
We did a test donation here. When the thank you message comes up, can we add more space between the logo and the first sentence and can this all be left aligned? See screen grab attached.
![screen shot 2015-11-18 at 1 28 24 pm 6](https://cloud.githubusercontent.com/assets/5920375/11250515/cc75cf38-8dfa-11e5-82a0-f13db81a97d6.png)

**Comment by therealgardenia** [comment]
@kylamedina Can you upload a screenshot?

**Comment by kylamedina** [comment]
<img width="1269" alt="screenshot 2015-11-19 15 02 15" src="https://cloud.githubusercontent.com/assets/1031900/11282681/99af83b2-8ece-11e5-89b7-14729d8dedb4.png">
